
language: node_js

node_js:
  - "6"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

# addons:
#   sauce_connect: true

script:
  - npm test
    # - npm run selenium

after_success:
  - cat ./coverage/*/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - ./scripts/sauce.sh

before_install:
  - openssl aes-256-cbc -K $encrypted_b3ecc378ff3b_key -iv $encrypted_b3ecc378ff3b_iv -in scripts/travis.enc -out scripts/travis -d
